spring.application.name=EduSphere_server
server.port=8080

# ?????
spring.datasource.url=jdbc:mysql://10.168.89.204:3306/Edu_Sphere?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
spring.datasource.username=root
spring.datasource.password=Huawei@311
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ???? (?????????????)
spring.mail.host=smtp.exmail.qq.com
spring.mail.port=465
spring.mail.username=3122230220@gnust.edu.cn
spring.mail.password=8Yhh8JZxo4k6H6M5
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=true

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.lx.edusphere_server.entity